rm \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F41Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F83Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F16Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/G28Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/GCodeProcessor.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F82Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F11Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F61Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/Command.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F42Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F32Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/PinControl.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F43Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/farmbot_arduino_controller.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F13Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F42Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/MemoryFree.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/StepperControlEncoder.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F20Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F12Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F81Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/GCodeHandler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/StepperControlEncoder.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F81Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/TimerOne.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F21Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/CurrentState.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F84Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/StepperControl.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F22Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F31Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F14Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F44Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/TimerOne.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/CurrentState.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F83Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/GCodeHandler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/PinGuardPin.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F16Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/StatusList.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F41Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/ServoControl.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/G28Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F61Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F11Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F22Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/farmbot_arduino_controller.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/PinControl.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/Command.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/G00Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F12Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/PinGuard.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F15Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/ParameterList.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/GCodeHandler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F21Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/StepperControl.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F31Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F44Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F15Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/StepperControlAxis.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/PinGuardPin.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F83Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/ServoControl.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F16Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F22Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/GCodeProcessor.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/G28Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F82Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F61Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F09Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/Command.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/StatusList.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F32Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F43Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/farmbot_arduino_controller.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F11Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F13Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/G00Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F42Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F09Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F20Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F12Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/PinGuard.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/ParameterList.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F15Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F84Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/MemoryFree.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/StepperControl.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F21Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/PinGuard.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F31Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F14Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/TimerOne.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F44Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/StepperControlAxis.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/PinGuardPin.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/F41Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/ServoControl.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/GCodeProcessor.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F82Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F32Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/StatusList.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/ParameterList.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F13Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/PinControl.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F43Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/G00Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F09Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F20Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/MemoryFree.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F14Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/F84Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_v10/StepperControlEncoder.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/F81Handler.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/ramps_v14/StepperControlAxis.o \
/home/connor/farmbot/farmbot-arduino-firmware/_build/farmduino_k14/CurrentState.o
